[images]
  remote_images = ["https://media.printables.com/media/prints/.*", "https://cdn.thingiverse.com/assets/.*", "https://thangs.com/_next/image.*", "https://makerworld.bblmw.com/makerworld/model/.*", "https://flightpack.eu/cdn/.*", "https://vow.systems/cdn/.*", "https://github.com/techfoundrynz/Pubmote/.*", "https://github.com/PickleWorks-Design/Hall-Sensor-Board/.*"]

[dev]
  targetPort = 8000